name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  flake:
    name: Flake self-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@v5
      with:
        fail-mode: true
  build:
    name: Build
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Build on ${{ matrix.host }}
      run: 'nix build -L .#'
    strategy:
      matrix:
        host:
        - macos-aarch64
        - linux
        include:
        - host: linux
          runs-on: ubuntu-latest
          timeout: 20
        - host: macos-aarch64
          runs-on: macos-latest
          timeout: 20
    timeout-minutes: ${{ matrix.timeout }}

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Cargo Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          path: ~/.cargo
      - name: Run flake checks (fmt, clippy, audit, ...)
        run: 'nix flake check'
